// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkoUmgtRLYFOImTWfxAdznGWe5mdkydaw',
    appId: '1:98602016873:web:48e02fe9936dfc0eff02f8',
    messagingSenderId: '98602016873',
    projectId: 'zakoota-e4451',
    authDomain: 'zakoota-e4451.firebaseapp.com',
    storageBucket: 'zakoota-e4451.firebasestorage.app',
    measurementId: 'G-FM3NS9QQJD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHlqRNMF4bvHDYLY2RyJ_gYVISYfMbyes',
    appId: '1:98602016873:android:129be10b1d543933ff02f8',
    messagingSenderId: '98602016873',
    projectId: 'zakoota-e4451',
    storageBucket: 'zakoota-e4451.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZlxccNTcRKEJa3-SjynJfy-OAntoE9Wc',
    appId: '1:98602016873:ios:d3d94b744c7c8ae3ff02f8',
    messagingSenderId: '98602016873',
    projectId: 'zakoota-e4451',
    storageBucket: 'zakoota-e4451.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZlxccNTcRKEJa3-SjynJfy-OAntoE9Wc',
    appId: '1:98602016873:ios:d3d94b744c7c8ae3ff02f8',
    messagingSenderId: '98602016873',
    projectId: 'zakoota-e4451',
    storageBucket: 'zakoota-e4451.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkoUmgtRLYFOImTWfxAdznGWe5mdkydaw',
    appId: '1:98602016873:web:1174a6b4343abc1dff02f8',
    messagingSenderId: '98602016873',
    projectId: 'zakoota-e4451',
    authDomain: 'zakoota-e4451.firebaseapp.com',
    storageBucket: 'zakoota-e4451.firebasestorage.app',
    measurementId: 'G-1YD94RZQDD',
  );

}